import type { Lesson } from "@/types";

const S2 = (term: string, theme: string, topicNumber: number, topicName: string, competency: string) => ({
  subject: "Mathematics", level: "S2", term, theme, topicNumber, topicName, competency,
});

export const s2MathLessons: Lesson[] = [
  {
    id: "s2-math-mappings", topicId: "s2-mappings", subjectId: "mathematics",
    title: "Mappings and relations", order: 1, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 1", "Patterns and Algebra", 1, "Mappings and Relations", "The learner represents and interprets mappings and relations."),
    blocks: [
      { type: "competency", text: "The learner should be able to represent and interpret mappings and relations." },
      { type: "outcome", text: "Define and identify mappings.", tag: "k" },
      { type: "outcome", text: "Represent mappings using diagrams, tables, and equations.", tag: "u,s" },
      { type: "context", heading: "Mappings connect inputs to outputs", content: "A mapping is a rule that takes an input and gives an output. When a shopkeeper multiplies the number of items by the price, that is a mapping. Understanding mappings is the foundation of functions, which you will use throughout mathematics." },
      { type: "key_point", title: "Types of mappings", content: "ONE-TO-ONE: each input maps to exactly one unique output. MANY-TO-ONE: multiple inputs map to the same output. ONE-TO-MANY: one input maps to multiple outputs (not a function). Example of one-to-one: y = 2x. Example of many-to-one: y = x^2." },
      { type: "worked_example", problem: "Given the mapping y = 3x - 1, find the outputs for inputs 0, 1, 2, 3.", steps: ["x=0: y = 3(0)-1 = -1", "x=1: y = 3(1)-1 = 2", "x=2: y = 3(2)-1 = 5", "x=3: y = 3(3)-1 = 8"], answer: "-1, 2, 5, 8", reasoning: "Each input gives exactly one output. This is a one-to-one mapping (a function)." },
      { type: "question", question: "In the mapping y = 2x + 3, what is y when x = 4?", options: ["8", "11", "7", "14"], correctIndex: 1, explanation: "y = 2(4) + 3 = 11." },
      { type: "question", question: "Which is a one-to-one mapping?", options: ["y = x^2", "y = 2x", "y = |x|", "y = x^2 + 1"], correctIndex: 1, explanation: "y = 2x gives each input a unique output. y = x^2 is many-to-one (e.g., both 2 and -2 give 4)." },
      { type: "question", question: "For y = x^2, what are the outputs for x = 2 and x = -2?", options: ["4 and -4", "4 and 4", "2 and -2", "4 and 2"], correctIndex: 1, explanation: "Both 2^2 = 4 and (-2)^2 = 4. This is many-to-one." },
      { type: "activity_of_integration", title: "The price mapping", scenario: "A shop sells mangoes at 500 UGX each.", task: "Write the mapping for total cost y for x mangoes. What type of mapping is it?", answer: "y = 500x. It is one-to-one: each number of mangoes gives a unique cost." },
    ],
  },
  {
    id: "s2-math-vectors", topicId: "s2-vectors", subjectId: "mathematics",
    title: "Vectors and translation", order: 2, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 1", "Patterns and Algebra", 2, "Vectors and Translation", "The learner represents and uses vectors."),
    blocks: [
      { type: "competency", text: "The learner should be able to represent and use vectors in two dimensions." },
      { type: "outcome", text: "Define and represent vectors.", tag: "k" },
      { type: "outcome", text: "Add and subtract vectors.", tag: "u,s" },
      { type: "context", heading: "Vectors have direction", content: "A vector is a quantity with both size (magnitude) and direction. Wind speed and direction is a vector. A boda boda going 40 km/h northeast is a vector. Understanding vectors is essential for navigation, physics, and engineering." },
      { type: "key_point", title: "Vectors vs scalars", content: "SCALAR: magnitude only (mass, temperature, speed). VECTOR: magnitude AND direction (force, velocity, displacement). Written as a column (x, y) or with an arrow on top." },
      { type: "worked_example", problem: "Add vectors a = (3, 1) and b = (1, 4).", steps: ["Add x-components: 3 + 1 = 4.", "Add y-components: 1 + 4 = 5.", "Result: (4, 5)."], answer: "(4, 5)", reasoning: "Vector addition is component by component. Think of walking 3 right and 1 up, then 1 right and 4 more up. Total: 4 right and 5 up." },
      { type: "question", question: "Which is a vector quantity?", options: ["Mass", "Temperature", "Velocity", "Time"], correctIndex: 2, explanation: "Velocity has both magnitude and direction. The others are scalars." },
      { type: "question", question: "Add (2, 3) + (4, 1).", options: ["(6, 4)", "(2, 2)", "(6, 3)", "(8, 3)"], correctIndex: 0, explanation: "2+4=6, 3+1=4. Result: (6, 4)." },
      { type: "question", question: "Which is a scalar quantity?", options: ["Force", "Displacement", "Speed", "Velocity"], correctIndex: 2, explanation: "Speed has magnitude only (no direction). It is a scalar." },
      { type: "activity_of_integration", title: "Navigation with vectors", scenario: "A boat crosses a river. The engine pushes it north at 3 m/s. The current pushes it east at 4 m/s.", task: "Find the resultant velocity vector. How fast and in what direction does the boat actually move?", hint: "Use Pythagoras for the magnitude.", answer: "Vectors: (4, 3). Speed = sqrt(4^2 + 3^2) = sqrt(25) = 5 m/s. Direction: northeast (atan(3/4) from east). The boat moves at 5 m/s in a diagonal direction, not straight north." },
    ],
  },
  {
    id: "s2-math-graphs", topicId: "s2-graphs", subjectId: "mathematics",
    title: "Graphs of linear functions", order: 3, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 1", "Data and Probability", 3, "Graphs", "The learner draws and interprets graphs of linear functions."),
    blocks: [
      { type: "competency", text: "The learner should be able to draw and interpret graphs of linear functions." },
      { type: "outcome", text: "Plot linear graphs from equations.", tag: "k,s" },
      { type: "outcome", text: "Determine gradient and y-intercept from a graph.", tag: "u" },
      { type: "key_point", title: "y = mx + c", content: "m = gradient (slope). c = y-intercept. Gradient = rise/run = (change in y) / (change in x)." },
      { type: "worked_example", problem: "Find the gradient of the line passing through (1, 3) and (4, 12).", steps: ["Gradient = (y2 - y1) / (x2 - x1).", "= (12 - 3) / (4 - 1).", "= 9 / 3 = 3."], answer: "Gradient = 3", reasoning: "The gradient tells you how steep the line is. A gradient of 3 means y increases by 3 for every 1 increase in x." },
      { type: "question", question: "Gradient of line through (0, 2) and (3, 8)?", options: ["2", "3", "6", "8/3"], correctIndex: 0, explanation: "(8-2)/(3-0) = 6/3 = 2." },
      { type: "question", question: "In y = -2x + 5, the gradient is?", options: ["5", "-2", "2", "3"], correctIndex: 1, explanation: "m = -2 (the line goes downward)." },
      { type: "question", question: "A horizontal line has gradient?", options: ["0", "1", "Undefined", "Infinity"], correctIndex: 0, explanation: "No vertical change = gradient 0." },
      { type: "activity_of_integration", title: "Mobile data costs", scenario: "A network charges 1,000 UGX per GB of data plus a 2,000 UGX daily access fee.", task: "Write the equation. How much for 5 GB? Graph this relationship.", answer: "y = 1000x + 2000. For 5 GB: y = 7000 UGX. Gradient = 1000 (rate per GB). Intercept = 2000 (fixed fee)." },
    ],
  },
  {
    id: "s2-math-indices", topicId: "s2-indices-logarithms", subjectId: "mathematics",
    title: "Indices and logarithms", order: 4, estimatedMinutes: 16, passingScore: 70, isActive: true,
    curriculum: S2("Term 1", "Numbers", 4, "Indices and Logarithms", "The learner uses indices and logarithms."),
    blocks: [
      { type: "competency", text: "The learner should be able to use the laws of indices and logarithms to simplify expressions." },
      { type: "outcome", text: "Apply the laws of indices.", tag: "u,s" },
      { type: "outcome", text: "Evaluate simple logarithms.", tag: "k,s" },
      { type: "key_point", title: "Laws of indices", content: "a^m x a^n = a^(m+n). a^m / a^n = a^(m-n). (a^m)^n = a^(mn). a^0 = 1. a^(-n) = 1/a^n. a^(1/n) = nth root of a." },
      { type: "worked_example", problem: "Simplify: 2^3 x 2^4", steps: ["Same base, add indices: 2^(3+4).", "= 2^7 = 128."], answer: "128", reasoning: "When multiplying powers with the same base, add the indices." },
      { type: "worked_example", problem: "Simplify: x^5 / x^2", steps: ["Same base, subtract indices: x^(5-2).", "= x^3."], answer: "x^3", reasoning: "When dividing powers with the same base, subtract the indices." },
      { type: "key_point", title: "Logarithms", content: "A logarithm answers: 'what power do I raise the base to, to get this number?' log(100) base 10 = 2 because 10^2 = 100. log(x) + log(y) = log(xy). log(x) - log(y) = log(x/y)." },
      { type: "question", question: "Simplify: 3^2 x 3^3", options: ["3^5", "3^6", "9^5", "6^5"], correctIndex: 0, explanation: "Add indices: 3^(2+3) = 3^5." },
      { type: "question", question: "Simplify: 2^5 / 2^3", options: ["2^2", "2^8", "2^15", "1^2"], correctIndex: 0, explanation: "Subtract indices: 2^(5-3) = 2^2 = 4." },
      { type: "question", question: "What is 5^0?", options: ["0", "1", "5", "Undefined"], correctIndex: 1, explanation: "Any number to the power 0 equals 1." },
      { type: "question", question: "log(1000) base 10 = ?", options: ["1", "2", "3", "10"], correctIndex: 2, explanation: "10^3 = 1000, so log(1000) = 3." },
      { type: "activity_of_integration", title: "Compound growth", scenario: "A savings account pays 10% interest per year. 100,000 UGX is deposited.", task: "After 3 years, the amount is 100,000 x 1.1^3. Calculate this. What is the power (index) doing?", answer: "1.1^3 = 1.331. Amount = 133,100 UGX. The index 3 represents 3 years of compounding. Each year multiplies by 1.1 (adding 10%). This is indices applied to finance." },
    ],
  },
  {
    id: "s2-math-inequalities", topicId: "s2-inequalities", subjectId: "mathematics",
    title: "Inequalities and regions", order: 5, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 2", "Patterns and Algebra", 5, "Inequalities", "The learner solves and represents inequalities."),
    blocks: [
      { type: "competency", text: "The learner should be able to solve linear inequalities and represent regions on graphs." },
      { type: "outcome", text: "Solve linear inequalities.", tag: "u,s" },
      { type: "outcome", text: "Represent inequalities graphically.", tag: "u,s" },
      { type: "key_point", title: "Solving inequalities", content: "Treat like equations BUT: when you multiply or divide by a negative number, FLIP the inequality sign. x > 3 becomes x < -3 if you multiply both sides by -1." },
      { type: "worked_example", problem: "Solve: -2x + 5 > 11", steps: ["Subtract 5: -2x > 6.", "Divide by -2: FLIP the sign.", "x < -3."], answer: "x < -3", reasoning: "Dividing by a negative number reverses the inequality. This is the most common mistake in UNEB exams. Always flip when multiplying/dividing by a negative." },
      { type: "question", question: "Solve: x + 4 < 10", options: ["x < 6", "x > 6", "x < 14", "x < -6"], correctIndex: 0, explanation: "Subtract 4: x < 6." },
      { type: "question", question: "Solve: -3x < 9", options: ["x < 3", "x > -3", "x < -3", "x > 3"], correctIndex: 1, explanation: "Divide by -3 and FLIP: x > -3." },
      { type: "question", question: "Solve: 2x - 3 > 7", options: ["x > 2", "x > 5", "x > 10", "x > 4"], correctIndex: 1, explanation: "Add 3: 2x > 10. Divide by 2: x > 5." },
      { type: "activity_of_integration", title: "Budget constraint", scenario: "A student has 50,000 UGX. Each book costs 8,000 UGX.", task: "Write an inequality for the number of books x they can buy. Solve it.", answer: "8000x <= 50000. x <= 6.25. The student can buy at most 6 books (can't buy a fraction)." },
    ],
  },
  {
    id: "s2-math-algebra2", topicId: "s2-algebra-2", subjectId: "mathematics",
    title: "Algebra 2: changing the subject", order: 6, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 2", "Patterns and Algebra", 6, "Algebra 2", "The learner changes the subject of a formula."),
    blocks: [
      { type: "competency", text: "The learner should be able to change the subject of a formula and solve simultaneous equations." },
      { type: "outcome", text: "Change the subject of a formula.", tag: "u,s" },
      { type: "outcome", text: "Solve simultaneous equations by substitution and elimination.", tag: "u,s" },
      { type: "key_point", title: "Changing the subject", content: "To make a different variable the subject, use inverse operations. Whatever you do to one side, do to the other. The goal is to isolate the new subject." },
      { type: "worked_example", problem: "Make r the subject of A = pi * r^2 (area of a circle).", steps: ["Divide both sides by pi: r^2 = A/pi.", "Square root both sides: r = sqrt(A/pi)."], answer: "r = sqrt(A/pi)", reasoning: "This is the reverse of the area formula. By undoing the operations (divide by pi, then square root), we isolate r." },
      { type: "worked_example", problem: "Solve simultaneously: 2x + y = 10 and x - y = 2", steps: ["Add the equations: (2x + y) + (x - y) = 10 + 2.", "3x = 12, so x = 4.", "Substitute x = 4 into the second equation: 4 - y = 2.", "y = 2.", "Answer: x = 4, y = 2."], answer: "x = 4, y = 2", reasoning: "By adding the equations, the y terms cancel (elimination). This is why the method is called elimination." },
      { type: "question", question: "Make x the subject: y = 3x + 2", options: ["x = (y-2)/3", "x = (y+2)/3", "x = 3y - 2", "x = y/3 + 2"], correctIndex: 0, explanation: "Subtract 2: y - 2 = 3x. Divide by 3: x = (y-2)/3." },
      { type: "question", question: "Solve: 3x + y = 7 and x + y = 3", options: ["x=2, y=1", "x=1, y=4", "x=3, y=-2", "x=2, y=-1"], correctIndex: 0, explanation: "Subtract: 2x = 4, x = 2. Then y = 3 - 2 = 1." },
      { type: "question", question: "Make b the subject: A = bh/2", options: ["b = A/h", "b = 2A/h", "b = A/2h", "b = 2h/A"], correctIndex: 1, explanation: "Multiply by 2: 2A = bh. Divide by h: b = 2A/h." },
      { type: "activity_of_integration", title: "Speed, distance, time", scenario: "The formula d = st links distance, speed, and time.", task: "Rearrange to make: (a) speed the subject, (b) time the subject. When would you use each?", answer: "(a) s = d/t (find speed given distance and time). (b) t = d/s (find time given distance and speed). Rearranging formulas lets you calculate any quantity when you know the other two." },
    ],
  },
  {
    id: "s2-math-similarity", topicId: "s2-similarity", subjectId: "mathematics",
    title: "Similarity and enlargement", order: 7, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 2", "Geometry and Measures", 7, "Similarity and Enlargement", "The learner uses scale factors for similarity and enlargement."),
    blocks: [
      { type: "competency", text: "The learner should be able to determine and use scale factors for similar figures and enlargements." },
      { type: "outcome", text: "Find scale factors of similar shapes.", tag: "u,s" },
      { type: "outcome", text: "Calculate areas and volumes of similar figures.", tag: "u,s" },
      { type: "key_point", title: "Scale factor", content: "When shapes are similar, all lengths are multiplied by the same scale factor (k). Area scales by k^2. Volume scales by k^3. Example: if lengths double (k=2), area is 4 times (2^2), volume is 8 times (2^3)." },
      { type: "worked_example", problem: "Two similar triangles. Small one has area 10 cm2. Scale factor is 3. Find the area of the large one.", steps: ["Area scales by k^2.", "k = 3, so k^2 = 9.", "Large area = 10 x 9 = 90 cm2."], answer: "90 cm2", reasoning: "Lengths triple, so area increases by 3^2 = 9. This is why area and volume scaling uses squared and cubed scale factors." },
      { type: "question", question: "Scale factor 2. How many times bigger is the area?", options: ["2", "4", "8", "16"], correctIndex: 1, explanation: "Area scales by 2^2 = 4." },
      { type: "question", question: "Scale factor 3. Volume is how many times bigger?", options: ["3", "9", "27", "81"], correctIndex: 2, explanation: "Volume scales by 3^3 = 27." },
      { type: "question", question: "Two similar cubes. Small has volume 8 cm3. Scale factor 2. Large volume?", options: ["16", "32", "64", "128"], correctIndex: 2, explanation: "Volume scales by 2^3 = 8. 8 x 8 = 64 cm3." },
      { type: "activity_of_integration", title: "Model to reality", scenario: "An architect builds a scale model of a building at 1:100 scale.", task: "If the model is 30 cm tall, how tall is the real building? If the model's floor area is 200 cm2, what is the real floor area?", answer: "Height: 30 x 100 = 3000 cm = 30 m. Area: scales by 100^2 = 10,000. Real area = 200 x 10,000 = 2,000,000 cm2 = 200 m2. Length scales linearly but area scales by the square." },
    ],
  },
  {
    id: "s2-math-circle", topicId: "s2-circle", subjectId: "mathematics",
    title: "The circle", order: 8, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S2("Term 2", "Geometry and Measures", 8, "Circle", "The learner uses the properties of circles."),
    blocks: [
      { type: "competency", text: "The learner should be able to calculate circumference and area of circles and use circle properties." },
      { type: "outcome", text: "Calculate circumference and area.", tag: "u,s" },
      { type: "outcome", text: "Use pi in calculations.", tag: "k,s" },
      { type: "key_point", title: "Circle formulas", content: "Circumference = pi x d = 2 x pi x r. Area = pi x r^2. pi = 3.14 (approximately). d = diameter, r = radius (r = d/2)." },
      { type: "worked_example", problem: "A circle has radius 7 cm. Find its circumference and area. (Use pi = 22/7)", steps: ["Circumference = 2 x (22/7) x 7 = 44 cm.", "Area = (22/7) x 7^2 = (22/7) x 49 = 154 cm2."], answer: "Circumference 44 cm, Area 154 cm2", reasoning: "Circumference is the distance around the circle. Area is the space inside it. When the radius is a multiple of 7, using pi = 22/7 makes the arithmetic clean." },
      { type: "question", question: "Circumference of a circle with r = 5? (pi = 3.14)", options: ["15.7", "31.4", "78.5", "10"], correctIndex: 1, explanation: "C = 2 x 3.14 x 5 = 31.4 cm." },
      { type: "question", question: "Area of a circle with r = 3? (pi = 3.14)", options: ["9.42", "18.84", "28.26", "6"], correctIndex: 2, explanation: "A = 3.14 x 3^2 = 3.14 x 9 = 28.26." },
      { type: "question", question: "Diameter = 10 cm. Radius = ?", options: ["5", "10", "20", "31.4"], correctIndex: 0, explanation: "Radius = diameter / 2 = 5 cm." },
      { type: "activity_of_integration", title: "Circular garden", scenario: "A farmer wants to put a fence around a circular garden with radius 14 m.", task: "How much fencing is needed? If fencing costs 2,000 UGX per metre, what is the total cost? (pi = 22/7)", answer: "Circumference = 2 x (22/7) x 14 = 88 m. Cost = 88 x 2,000 = 176,000 UGX. This is circumference applied to a real budgeting problem." },
    ],
  },
  {
    id: "s2-math-set-theory", topicId: "s2-set-theory", subjectId: "mathematics",
    title: "Set theory", order: 9, estimatedMinutes: 16, passingScore: 70, isActive: true,
    curriculum: S2("Term 3", "Data and Probability", 9, "Set Theory", "The learner uses set notation and Venn diagrams."),
    blocks: [
      { type: "competency", text: "The learner should be able to use set notation, set operations, and Venn diagrams to solve problems." },
      { type: "outcome", text: "Use set notation (union, intersection, complement).", tag: "k,u" },
      { type: "outcome", text: "Solve problems using Venn diagrams.", tag: "u,s" },
      { type: "context", heading: "Sets organise groups", content: "A set is a collection of items. The set of students who play football. The set who play basketball. Some play both. Set theory helps us count and organise overlapping groups. It is used in databases, surveys, and probability." },
      { type: "key_point", title: "Set operations", content: "UNION (A or B): all items in A, B, or both. Written A union B. INTERSECTION (A and B): only items in BOTH A and B. Written A intersect B. COMPLEMENT (A'): items NOT in A. UNIVERSAL SET: everything under consideration." },
      { type: "worked_example", problem: "In a class of 30: 18 study Maths, 15 study Physics, 7 study both. How many study neither?", steps: ["Draw a Venn diagram with two overlapping circles.", "Both = 7 (in the intersection).", "Maths only = 18 - 7 = 11.", "Physics only = 15 - 7 = 8.", "Total studying at least one = 11 + 7 + 8 = 26.", "Neither = 30 - 26 = 4."], answer: "4 students study neither", reasoning: "The Venn diagram helps you avoid double-counting the 7 who study both. You subtract them from each subject's total, then add the parts." },
      { type: "question", question: "A union B means?", options: ["Items in both A and B", "Items in A, B, or both", "Items in neither", "Items only in A"], correctIndex: 1, explanation: "Union combines everything in either set." },
      { type: "question", question: "A intersect B means?", options: ["Items in both A and B only", "Items in A or B", "All items", "Items not in A"], correctIndex: 0, explanation: "Intersection is only items in BOTH sets." },
      { type: "question", question: "Class of 40. 20 like tea, 15 like coffee, 5 like both. How many like neither?", options: ["5", "10", "15", "20"], correctIndex: 1, explanation: "Tea only = 15, coffee only = 10, both = 5. Total = 30. Neither = 40-30 = 10." },
      { type: "activity_of_integration", title: "Sports survey", scenario: "A school surveys 50 students. 30 play football, 25 play netball, 10 play both. How many play at least one sport? How many play neither?", answer: "Football only = 20, netball only = 15, both = 10. At least one = 45. Neither = 50 - 45 = 5. This is set theory applied to real data analysis." },
    ],
  },
];
