import type { Lesson } from "@/types";

const S1 = (term: string, theme: string, topicNumber: number, topicName: string, competency: string) => ({
  subject: "Physics", level: "S1", term, theme, topicNumber, topicName, competency,
});

export const physicsLessons: Lesson[] = [
  {
    id: "s1-phys-introduction", topicId: "phys-introduction", subjectId: "physics",
    title: "Introduction to Physics", order: 1, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S1("Term 1", "Introduction", 1, "Introduction to Physics", "The learner understands the importance of Physics and safe laboratory practice."),
    blocks: [
      { type: "competency", text: "The learner should understand the importance of Physics and safe laboratory practice." },
      { type: "outcome", text: "Understand the meaning of Physics and its branches.", tag: "u" },
      { type: "context", heading: "Physics explains the world", content: "Physics studies matter, energy, and their interactions. Every technology, from a bicycle to a satellite, is built on physics." },
      { type: "key_point", title: "Branches", content: "Mechanics, Heat, Light/Optics, Sound, Electricity, Nuclear, Astrophysics." },
      { type: "question", question: "Physics is the study of?", options: ["Living things", "Matter and energy", "Chemicals", "Numbers"], correctIndex: 1, explanation: "Matter, energy, interactions." },
      { type: "question", question: "Which branch deals with motion and forces?", options: ["Optics", "Mechanics", "Acoustics", "Nuclear"], correctIndex: 1, explanation: "Mechanics." },
      { type: "question", question: "Which is NOT a branch of Physics?", options: ["Mechanics", "Botany", "Optics", "Thermodynamics"], correctIndex: 1, explanation: "Botany is Biology." },
      { type: "activity_of_integration", title: "Physics in your day", scenario: "Physics is at work every moment.", task: "List five examples of physics in daily life with their branch.", answer: "Boiling water (heat), boda boda (mechanics), light switch (electricity), hearing bells (sound), phone (electromagnetism)." },
    ],
  },
  {
    id: "s1-phys-measurements", topicId: "phys-measurements", subjectId: "physics",
    title: "Measurements in Physics", order: 2, estimatedMinutes: 18, passingScore: 70, isActive: true,
    curriculum: S1("Term 1", "Mechanics", 2, "Measurements", "The learner measures physical quantities in SI units."),
    blocks: [
      { type: "competency", text: "The learner should estimate and measure length, area, volume, mass, density, and time in SI units." },
      { type: "outcome", text: "Identify physical quantities and their SI units.", tag: "k,u" },
      { type: "outcome", text: "Calculate density.", tag: "u,s" },
      { type: "key_point", title: "SI units", content: "Length: metre (m). Mass: kilogram (kg). Time: second (s). Temperature: Kelvin (K). Force: Newton (N)." },
      { type: "worked_example", problem: "Block: 10cm x 5cm x 3cm, mass 120g. Find volume and density.", steps: ["Volume = 10 x 5 x 3 = 150 cm3.", "Density = 120/150 = 0.8 g/cm3."], answer: "Volume 150 cm3, Density 0.8 g/cm3", reasoning: "0.8 < 1.0 so it floats in water." },
      { type: "question", question: "SI unit of mass?", options: ["Gram", "Kilogram", "Newton", "Litre"], correctIndex: 1, explanation: "Kilogram." },
      { type: "question", question: "Density: mass 240g, volume 80cm3?", options: ["2", "3", "4", "0.33"], correctIndex: 1, explanation: "240/80 = 3." },
      { type: "question", question: "Density 0.8 in water (1.0). It will?", options: ["Sink", "Float", "Dissolve", "Stay middle"], correctIndex: 1, explanation: "0.8 < 1.0 floats." },
      { type: "activity_of_integration", title: "Why ships float", scenario: "Steel sinks but ships float.", task: "Explain using density.", answer: "Ships are hollow (air inside). Average density of steel + air < 1.0. If filled with water, they sink." },
    ],
  },
  {
    id: "s1-phys-states-matter", topicId: "phys-states-matter", subjectId: "physics",
    title: "States of matter (Physics)", order: 3, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S1("Term 2", "Mechanics and Properties of Matter", 3, "States of Matter", "The learner uses the particle theory to explain states of matter."),
    blocks: [
      { type: "competency", text: "The learner should be able to use knowledge of particle arrangement and motion to explain the states of matter." },
      { type: "outcome", text: "Describe solids, liquids and gases using particle theory.", tag: "u" },
      { type: "outcome", text: "Explain how pressure relates to particle behaviour.", tag: "u" },
      { type: "context", heading: "Particles and pressure", content: "Why does a balloon burst when you blow too much air in? The particles push against the walls. Understanding how particles behave explains pressure, which is how tyres, pumps, and weather work." },
      { type: "key_point", title: "Particle theory basics", content: "All matter is particles in constant motion. Solids: particles vibrate in fixed positions. Liquids: particles slide past each other. Gases: particles move freely at high speed. Heating increases particle energy." },
      { type: "key_point", title: "Pressure", content: "Pressure is force per unit area. Formula: Pressure = Force / Area. Unit: Pascals (Pa) or N/m2. Small area with same force = higher pressure. This is why sharp knives cut better than blunt ones." },
      { type: "worked_example", problem: "A box weighs 200 N. Its base area is 2 m2. Calculate the pressure it exerts.", steps: ["Pressure = Force / Area.", "P = 200 / 2 = 100 Pa."], answer: "100 Pascals", reasoning: "If the area were smaller (say 0.5 m2), the pressure would be 200/0.5 = 400 Pa. Smaller area means more pressure - this is why needles are sharp." },
      { type: "question", question: "In which state are particles closest together?", options: ["Solid", "Liquid", "Gas", "Plasma"], correctIndex: 0, explanation: "Solids have particles packed closely." },
      { type: "question", question: "Pressure = ?", options: ["Force x Area", "Force / Area", "Area / Force", "Force + Area"], correctIndex: 1, explanation: "Pressure = Force divided by Area." },
      { type: "question", question: "Why does a sharp knife cut better than a blunt one?", options: ["Heavier", "Smaller area means higher pressure", "More force", "Different material"], correctIndex: 1, explanation: "Small area concentrates force into higher pressure." },
      { type: "question", question: "Force 500 N spread over 5 m2. What is the pressure?", options: ["25 Pa", "100 Pa", "2500 Pa", "500 Pa"], correctIndex: 1, explanation: "500/5 = 100 Pa." },
      { type: "activity_of_integration", title: "Why camel feet matter", scenario: "Camels walk easily on sand while humans sink.", task: "Explain using pressure why camels do not sink into sand.", hint: "Compare the area of camel feet to human feet.", answer: "Camels have large, wide feet. This spreads their weight over a large area, reducing pressure on the sand. Humans have small feet, so the same weight creates more pressure and they sink. This is pressure applied in nature - and it is the same principle behind snowshoes." },
    ],
  },
  {
    id: "s1-phys-temperature", topicId: "phys-temperature", subjectId: "physics",
    title: "Temperature measurements", order: 4, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S1("Term 2", "Heat", 4, "Temperature Measurements", "The learner understands temperature and heat effects."),
    blocks: [
      { type: "competency", text: "The learner should appreciate that temperature change results from heat effects and that daily temperature changes affect our lives." },
      { type: "outcome", text: "Distinguish between heat and temperature.", tag: "u" },
      { type: "outcome", text: "Use thermometers and temperature scales.", tag: "k,s" },
      { type: "context", heading: "Heat vs Temperature", content: "A bath of warm water has more heat than a cup of boiling water, but the cup is at a higher temperature. Heat is the total energy; temperature is how hot something is. Understanding this difference is essential for cooking, weather, and health." },
      { type: "key_point", title: "Heat vs Temperature", content: "HEAT: total thermal energy in a body. Measured in Joules (J). Depends on mass and temperature. TEMPERATURE: how hot or cold something is. Measured in degrees Celsius or Kelvin. Does not depend on mass. A large lake at 20 degrees has more heat than a cup at 90 degrees." },
      { type: "key_point", title: "Temperature scales", content: "Celsius: water freezes at 0 degrees, boils at 100 degrees. Kelvin: starts at absolute zero (-273 degrees C). K = C + 273. Clinical thermometer: measures body temperature (35-42 degrees C). Normal body temperature is 37 degrees C." },
      { type: "worked_example", problem: "Convert 25 degrees Celsius to Kelvin.", steps: ["K = C + 273.", "K = 25 + 273 = 298 K."], answer: "298 Kelvin", reasoning: "Kelvin starts at absolute zero, the lowest possible temperature. Adding 273 converts Celsius to Kelvin. This scale is used in physics because it has no negative values." },
      { type: "exam_style", scenario: "UNEB tests understanding of heat vs temperature.", question: "Distinguish between heat and temperature. A student says a lake at 15 degrees C has more heat than a cup of tea at 80 degrees C. Is the student correct? Explain.", marks: 4 },
      { type: "marking_guide", totalMarks: 4, criteria: [
        { criterion: "Heat: total energy, in Joules", marks: 1, type: "method" },
        { criterion: "Temperature: degree of hotness, in degrees", marks: 1, type: "method" },
        { criterion: "States student is correct", marks: 1, type: "accuracy" },
        { criterion: "Lake has more mass, so more total heat energy despite lower temperature", marks: 1, type: "communication" },
      ] },
      { type: "question", question: "Heat is measured in?", options: ["Degrees", "Joules", "Newtons", "Pascals"], correctIndex: 1, explanation: "Heat (energy) is in Joules." },
      { type: "question", question: "Temperature is measured in?", options: ["Joules", "Degrees Celsius or Kelvin", "Newtons", "Watts"], correctIndex: 1, explanation: "Temperature in degrees C or K." },
      { type: "question", question: "Convert 100 degrees C to Kelvin.", options: ["100 K", "273 K", "373 K", "473 K"], correctIndex: 2, explanation: "100 + 273 = 373 K." },
      { type: "question", question: "Normal human body temperature is?", options: ["30 C", "37 C", "42 C", "25 C"], correctIndex: 1, explanation: "37 degrees Celsius." },
      { type: "activity_of_integration", title: "Clinical thermometer", scenario: "A nurse checks a patient's temperature with a clinical thermometer.", task: "Why does a clinical thermometer have a small range (35-42 degrees C) and a kink (constriction)?", answer: "The small range gives high precision in the body temperature range. The kink prevents mercury from flowing back down after removal, so the reading stays at the maximum temperature. This is physics applied to medicine." },
    ],
  },
  {
    id: "s1-phys-heat-transfer", topicId: "phys-heat-transfer", subjectId: "physics",
    title: "Heat transfer", order: 5, estimatedMinutes: 16, passingScore: 70, isActive: true,
    curriculum: S1("Term 3", "Heat", 5, "Heat Transfer", "The learner explains the modes of heat transfer."),
    blocks: [
      { type: "competency", text: "The learner should be able to explain the modes of heat transfer and their applications to daily life." },
      { type: "outcome", text: "Describe conduction, convection, and radiation.", tag: "k,u" },
      { type: "outcome", text: "Give examples of each mode in daily life.", tag: "u,s" },
      { type: "context", heading: "How heat moves", content: "When you hold a metal spoon in hot soup, the handle gets warm. That is conduction. When water boils, the heat circulates. That is convection. The Sun warms the Earth across space. That is radiation. Heat moves in three ways, and understanding them explains cooking, weather, and insulation." },
      { type: "key_point", title: "Three modes of heat transfer", content: "CONDUCTION: heat passes through a solid (metal spoon in soup). Particles vibrate and pass energy to neighbours. Best in metals, worst in insulators like wood and plastic. CONVECTION: heat moves in fluids (liquids and gases) by circulation. Warm fluid rises, cool fluid sinks. RADIATION: heat travels as infrared waves. No medium needed. The Sun's heat reaches Earth through the vacuum of space." },
      { type: "worked_example", problem: "Explain how water heats up in a saucepan on a stove.", steps: ["The flame heats the bottom of the pan by conduction (metal conducts heat).", "Water at the bottom warms, expands, becomes less dense, and rises.", "Cooler water at the top sinks to replace it.", "This circulation (convection current) spreads heat through all the water."], answer: "Conduction through pan, then convection in the water", reasoning: "This is why you stir soup - it speeds up the convection process and distributes heat evenly. Without convection, only the bottom would get hot." },
      { type: "key_point", title: "Conductors and insulators", content: "GOOD CONDUCTORS: metals (copper, aluminium, iron). Used for cooking pots. INSULATORS (poor conductors): wood, plastic, glass, air. Used for saucepan handles (so you don't burn yourself) and building insulation. Air is an excellent insulator - this is why double-glazed windows trap air between panes." },
      { type: "exam_style", scenario: "UNEB tests knowledge of heat transfer modes with real-life examples.", question: "Name the three modes of heat transfer. For each, give one example from daily life in Uganda.", marks: 6 },
      { type: "marking_guide", totalMarks: 6, criteria: [
        { criterion: "Conduction named + example (cooking pot, metal spoon)", marks: 2, type: "method" },
        { criterion: "Convection named + example (boiling water, sea breeze)", marks: 2, type: "method" },
        { criterion: "Radiation named + example (sun warming earth, charcoal stove glow)", marks: 2, type: "accuracy" },
      ] },
      { type: "question", question: "Heat transfer through a solid metal is called?", options: ["Convection", "Conduction", "Radiation", "Insulation"], correctIndex: 1, explanation: "Conduction: heat passes through solids by particle vibration." },
      { type: "question", question: "Heat transfer by circulating fluids is called?", options: ["Conduction", "Convection", "Radiation", "Evaporation"], correctIndex: 1, explanation: "Convection: warm fluid rises, cool fluid sinks." },
      { type: "question", question: "Which mode does NOT need a medium?", options: ["Conduction", "Convection", "Radiation", "None"], correctIndex: 2, explanation: "Radiation travels through vacuum (space). The Sun's heat reaches Earth this way." },
      { type: "question", question: "Which is the best conductor of heat?", options: ["Wood", "Plastic", "Copper", "Air"], correctIndex: 2, explanation: "Copper is an excellent metal conductor. Used in cooking pots." },
      { type: "question", question: "Why are saucepan handles made of plastic?", options: ["Looks good", "Plastic is a good insulator", "Plastic is cheap", "Plastic conducts well"], correctIndex: 1, explanation: "Plastic is a poor conductor (insulator). It stops heat from reaching your hand." },
      { type: "activity_of_integration", title: "The charcoal stove", scenario: "In Uganda, many homes use charcoal stoves (sigiris) for cooking.", task: "Identify all three modes of heat transfer at work when cooking on a charcoal stove.", hint: "Think about the metal stove, the air circulation, and the glowing charcoal.", answer: "1. Conduction: heat passes through the metal pot and stove walls. 2. Convection: hot air rises from the charcoal, creating a draft that feeds oxygen to the fire (this is why stoves have ventilation holes). 3. Radiation: the glowing charcoal radiates infrared heat in all directions (you feel warmth on your face from the side). All three modes work simultaneously. This is physics happening in every Ugandan kitchen." },
    ],
  },
  {
    id: "s1-phys-expansion", topicId: "phys-expansion", subjectId: "physics",
    title: "Expansion of solids, liquids and gases", order: 6, estimatedMinutes: 14, passingScore: 70, isActive: true,
    curriculum: S1("Term 3", "Heat", 6, "Expansion", "The learner explains the effect of heat on expansion."),
    blocks: [
      { type: "competency", text: "The learner should be able to explain the effect of heat on the expansion of solids, liquids, and gases and explore practical applications." },
      { type: "outcome", text: "Describe expansion in solids, liquids, and gases.", tag: "k,u" },
      { type: "outcome", text: "Explain real-life applications and consequences of expansion.", tag: "u,s" },
      { type: "context", heading: "Why things expand when heated", content: "Railway tracks bend in hot weather. Bottle caps loosen when warmed. A balloon expands in the sun. When you heat a substance, its particles move faster and spread apart, taking up more space. This is thermal expansion, and it affects engineering, construction, and daily life." },
      { type: "key_point", title: "Expansion in different states", content: "GASES expand the most (particles already far apart, easy to spread). LIQUIDS expand moderately (particles close but can move). SOLIDS expand the least (particles in fixed positions, only vibrate more). But even small solid expansion matters in engineering (bridges, railway lines)." },
      { type: "key_point", title: "The bimetallic strip", content: "Two different metals bonded together expand at different rates when heated. This causes the strip to bend. This principle is used in thermostats (which switch off your iron when it reaches the right temperature) and fire alarms. Brass expands more than iron, so a brass-iron strip bends toward the iron side when heated." },
      { type: "worked_example", problem: "Why do railway engineers leave small gaps between sections of track?", steps: ["In hot weather, the steel rails absorb heat and expand.", "If there were no gaps, the expanding rails would push against each other.", "This force is enormous and would buckle (bend) the track.", "Gaps allow expansion without damage.", "This is why trains make a 'clack-clack' sound."], answer: "Gaps allow thermal expansion without buckling", reasoning: "Steel expands by about 12 millionths of a metre per metre per degree. Over a long track in African heat, this adds up to significant length. Without gaps, the tracks would buckle and cause derailments." },
      { type: "question", question: "Which expands most when heated?", options: ["Solid", "Liquid", "Gas", "All the same"], correctIndex: 2, explanation: "Gases expand the most. Particles are already far apart." },
      { type: "question", question: "Why are gaps left in railway tracks?", options: ["Save material", "Allow expansion in heat", "For drainage", "Make the clack sound"], correctIndex: 1, explanation: "Gaps prevent buckling from thermal expansion." },
      { type: "question", question: "A bimetallic strip bends when heated because?", options: ["One metal melts", "The metals expand at different rates", "Gravity changes", "Air pressure"], correctIndex: 1, explanation: "Different metals expand differently. The strip bends toward the metal that expands less." },
      { type: "question", question: "Why does a tight metal lid loosen when held under hot water?", options: ["Metal softens", "Metal expands", "Glass shrinks", "Water lubricates"], correctIndex: 1, explanation: "The hot water heats the metal lid, which expands and loosens its grip on the jar." },
      { type: "activity_of_integration", title: "Telephone wires in Uganda", scenario: "You notice telephone wires sag lower on hot days and are tighter on cold mornings.", task: "Explain why this happens using thermal expansion. What would happen if engineers installed the wires perfectly tight on a hot day?", answer: "On hot days, the wires expand (get longer) and sag. On cold mornings, they contract and become tighter. If engineers installed them tight on a hot day, they would contract and snap on a cold night. So they install them with some sag (loose) so there is room for contraction. This is thermal expansion applied to infrastructure engineering." },
    ],
  },
  {
    id: "s1-phys-forces", topicId: "phys-forces", subjectId: "physics",
    title: "Effects of forces", order: 7, estimatedMinutes: 16, passingScore: 70, isActive: true,
    curriculum: S1("Term 2", "Mechanics", 7, "Effects of Forces", "The learner understands forces and their effects."),
    blocks: [
      { type: "competency", text: "The learner should explain the effects of forces on objects and distinguish between types of forces." },
      { type: "outcome", text: "Define force and state its SI unit.", tag: "k" },
      { type: "outcome", text: "Distinguish between mass and weight.", tag: "u" },
      { type: "key_point", title: "What is a force?", content: "A push or pull. SI unit: Newton (N). Forces change shape, speed, or direction." },
      { type: "key_point", title: "Mass vs Weight", content: "MASS: amount of matter, in kg, constant. WEIGHT: force of gravity, in Newtons, varies. W = mg. On Earth g = 10 N/kg." },
      { type: "worked_example", problem: "Mass 50 kg. Calculate weight on Earth.", steps: ["W = mg = 50 x 10 = 500 N."], answer: "500 N", reasoning: "On the Moon (g=1.6), same mass weighs only 80 N." },
      { type: "question", question: "SI unit of force?", options: ["Kilogram", "Newton", "Joule", "Watt"], correctIndex: 1, explanation: "Newton (N)." },
      { type: "question", question: "Calculate weight: mass 30 kg, g = 10.", options: ["3", "30", "300", "3000"], correctIndex: 2, explanation: "30 x 10 = 300 N." },
      { type: "question", question: "Friction always opposes?", options: ["Gravity", "Motion", "Weight", "Mass"], correctIndex: 1, explanation: "Friction opposes motion." },
      { type: "activity_of_integration", title: "Wet roads", scenario: "Accidents increase when Kampala roads are wet.", task: "Explain why and suggest two safety measures.", answer: "Water reduces tyre friction. Drive slower, use good tyres, keep distance." },
    ],
  },
  {
    id: "s1-phys-light-reflection", topicId: "phys-light-reflection", subjectId: "physics",
    title: "Light and reflection", order: 8, estimatedMinutes: 16, passingScore: 70, isActive: true,
    curriculum: S1("Term 3", "Light", 8, "Light and Reflection", "The learner understands light and the laws of reflection."),
    blocks: [
      { type: "competency", text: "The learner should explain the nature of light and apply the laws of reflection at plane surfaces." },
      { type: "outcome", text: "State and apply the laws of reflection.", tag: "u,s" },
      { type: "key_point", title: "Laws of reflection", content: "1. Angle of incidence = angle of reflection (i = r). 2. Incident ray, reflected ray, and normal are in the same plane. Normal is at 90 degrees to the mirror." },
      { type: "worked_example", problem: "Light hits a mirror at 35 degrees to the normal. Angle of reflection?", steps: ["i = r.", "35 degrees."], answer: "35 degrees", reasoning: "The law of reflection is absolute." },
      { type: "question", question: "Light travels in?", options: ["Curves", "Straight lines", "Circles", "Waves"], correctIndex: 1, explanation: "Straight lines." },
      { type: "question", question: "Angle of incidence equals?", options: ["Angle of mirror", "Angle of reflection", "Angle of refraction", "90 degrees"], correctIndex: 1, explanation: "i = r." },
      { type: "question", question: "Incidence is 30 degrees. Reflection is?", options: ["15", "30", "60", "90"], correctIndex: 1, explanation: "i = r = 30." },
      { type: "activity_of_integration", title: "Periscope", scenario: "A periscope uses two mirrors at 45 degrees.", task: "Explain how it lets you see over obstacles.", answer: "Two reflections redirect light downward. Used in submarines and by soldiers." },
    ],
  },
];
