import type { Lesson } from "@/types";

const S1 = (term: string, theme: string, topicNumber: number, topicName: string, competency: string) => ({
  subject: "Biology", level: "S1", term, theme, topicNumber, topicName, competency,
});

export const biologyLessons: Lesson[] = [

  // ===== TOPIC 1: INTRODUCTION TO BIOLOGY =====
  {
    id: "s1-bio-introduction",
    topicId: "bio-introduction",
    subjectId: "biology",
    title: "Introduction to Biology",
    order: 1,
    estimatedMinutes: 16,
    passingScore: 70,
    isActive: true,
    curriculum: S1("Term 1", "Diversity of Living Things", 1, "Introduction to Biology",
      "The learner understands biology as a study of life and that all living organisms experience common life processes."),
    blocks: [
      { type: "competency", text: "The learner should understand that biology is the study of life and that all living organisms experience common life processes." },
      { type: "outcome", text: "Appreciate that biology is the study of life.", tag: "k" },
      { type: "outcome", text: "Understand that life processes are common to all living things but manifested differently.", tag: "u" },
      { type: "context", heading: "What is Biology?", content: "Biology is the study of living things. From 'bios' (life) and 'logos' (study). Everything alive, from grass to your own body, is studied in biology. Understanding it helps us make decisions about health, farming, and the environment." },
      { type: "key_point", title: "MRS GREN", content: "All living organisms share seven characteristics: Movement, Respiration, Sensitivity, Growth, Reproduction, Excretion, Nutrition. If something has all seven, it is living." },
      { type: "worked_example", problem: "Is a car living? Use MRS GREN.", steps: ["Movement: Yes.", "Respiration: No (no chemical energy release from food).", "Growth: No.", "Reproduction: No.", "Conclusion: Not living."], answer: "A car is not living", reasoning: "Movement alone does not make something alive. All seven characteristics must be present." },
      { type: "key_point", title: "Branches of Biology", content: "Botany (plants), Zoology (animals), Microbiology (microorganisms), Ecology (organisms and environment), Genetics (heredity), Anatomy (structure), Physiology (function)." },
      { type: "question", question: "What does M in MRS GREN stand for?", options: ["Movement", "Metabolism", "Memory", "Multiplication"], correctIndex: 0, explanation: "M = Movement." },
      { type: "question", question: "Which is NOT a characteristic of living things?", options: ["Respiration", "Photosynthesis", "Growth", "Excretion"], correctIndex: 1, explanation: "Photosynthesis is a process, not one of the seven universal characteristics." },
      { type: "question", question: "The study of plants is called?", options: ["Zoology", "Botany", "Ecology", "Genetics"], correctIndex: 1, explanation: "Botany = plants." },
      { type: "question", question: "Excretion refers to?", options: ["Taking in food", "Removing waste", "Growing", "Responding to light"], correctIndex: 1, explanation: "Excretion = removal of waste products." },
      { type: "activity_of_integration", title: "Is fire alive?", scenario: "Fire moves, grows, spreads, and uses fuel. Some argue it is alive.", task: "Use MRS GREN to determine whether fire is living.", hint: "Check all seven, not just some.", answer: "Fire lacks respiration, excretion, and true biological reproduction. It is NOT living." },
    ],
  },

  // ===== TOPIC 2: CELLS =====
  {
    id: "s1-bio-cells",
    topicId: "bio-cells",
    subjectId: "biology",
    title: "Cells: The building blocks of life",
    order: 2,
    estimatedMinutes: 18,
    passingScore: 70,
    isActive: true,
    curriculum: S1("Term 1", "Diversity of Living Things", 2, "Cells",
      "The learner appreciates the cell as the basic unit of living organisms."),
    blocks: [
      { type: "competency", text: "The learner should appreciate that a cell is the basic unit of living organisms, and how cell structures relate to their functions." },
      { type: "outcome", text: "Know the structure and functions of animal and plant cells.", tag: "k,u,s" },
      { type: "outcome", text: "Understand levels of organisation in organisms.", tag: "u" },
      { type: "context", heading: "Everything alive is made of cells", content: "Your body has billions of cells. A leaf is made of cells. Even bacteria are single cells. The cell is the basic unit of life, like a brick is the basic unit of a wall." },
      { type: "key_point", title: "Plant vs Animal cells", content: "Both have: nucleus, cytoplasm, cell membrane. PLANT cells also have: cell wall (cellulose, support), chloroplasts (photosynthesis), large vacuole (stores water)." },
      { type: "worked_example", problem: "Name three structures in a plant cell not found in an animal cell.", steps: ["Cell wall: rigid support made of cellulose.", "Chloroplasts: contain chlorophyll for photosynthesis.", "Large vacuole: stores water and maintains turgor pressure."], answer: "Cell wall, chloroplasts, large vacuole", reasoning: "These reflect plant survival needs: rigid support (no skeleton), self-feeding (photosynthesis), water storage (cannot move to find it)." },
      { type: "key_point", title: "Levels of organisation", content: "Cell forms tissue (similar cells). Tissue forms organ (different tissues). Organ forms system. System forms organism." },
      { type: "question", question: "Which part controls what enters and leaves the cell?", options: ["Nucleus", "Cell membrane", "Cytoplasm", "Vacuole"], correctIndex: 1, explanation: "Cell membrane is selectively permeable." },
      { type: "question", question: "Which structure is in plant cells but NOT animal cells?", options: ["Nucleus", "Cytoplasm", "Cell wall", "Cell membrane"], correctIndex: 2, explanation: "Cell wall = cellulose, plants only." },
      { type: "question", question: "Where does photosynthesis happen?", options: ["Nucleus", "Chloroplasts", "Vacuole", "Cell wall"], correctIndex: 1, explanation: "Chloroplasts contain chlorophyll." },
      { type: "question", question: "Correct order of organisation?", options: ["Organ, tissue, cell", "Cell, tissue, organ", "Tissue, cell, organ", "Cell, organ, tissue"], correctIndex: 1, explanation: "Cells form tissues, tissues form organs." },
      { type: "activity_of_integration", title: "Specialised cells", scenario: "A root hair cell has a long thin extension.", task: "Explain why its shape relates to its function.", hint: "Think about surface area and absorption.", answer: "The long extension increases surface area for absorbing water and minerals from soil. Structure matches function." },
    ],
  },

  // ===== TOPIC 3: CLASSIFICATION =====
  {
    id: "s1-bio-classification",
    topicId: "bio-classification",
    subjectId: "biology",
    title: "Classification of living things",
    order: 3,
    estimatedMinutes: 18,
    passingScore: 70,
    isActive: true,
    curriculum: S1("Term 1", "Diversity of Living Things", 3, "Classification",
      "The learner understands classification as sorting living things by similarities."),
    blocks: [
      { type: "competency", text: "The learner should understand that classification is the sorting out of living things based on their similarities and differences." },
      { type: "outcome", text: "Know the five kingdoms of living organisms.", tag: "k" },
      { type: "outcome", text: "Classify organisms into their correct kingdoms.", tag: "u,s" },
      { type: "context", heading: "Why classify?", content: "Imagine a library with no system. You could never find anything. Classification organises living things into groups based on similarities, making them easier to study and identify." },
      { type: "key_point", title: "The five kingdoms", content: "1. Animals (Animalia): multicellular, no cell walls, eat others. 2. Plants (Plantae): cell walls, chlorophyll, make own food. 3. Fungi: cell walls, feed on dead matter (mushrooms). 4. Protoctista: simple, mostly unicellular (amoeba). 5. Prokaryotes (Bacteria): no true nucleus." },
      { type: "key_point", title: "Vertebrate groups", content: "Fish (gills, scales, cold-blooded), Amphibians (moist skin, frog), Reptiles (dry scales, lizard), Birds (feathers, beak, warm-blooded), Mammals (hair, milk, warm-blooded)." },
      { type: "worked_example", problem: "Classify: mushroom, mango tree, housefly, amoeba, bacterium.", steps: ["Mushroom: feeds on dead matter = Fungi.", "Mango tree: has chlorophyll = Plantae.", "Housefly: multicellular, eats others = Animalia.", "Amoeba: unicellular with nucleus = Protoctista.", "Bacterium: no nucleus = Prokaryotes."], answer: "Fungi, Plantae, Animalia, Protoctista, Prokaryotes", reasoning: "Start with obvious features: cell walls? Makes own food? Unicellular? Has nucleus?" },
      { type: "question", question: "Which kingdom do mushrooms belong to?", options: ["Plantae", "Animalia", "Fungi", "Protoctista"], correctIndex: 2, explanation: "Mushrooms are fungi." },
      { type: "question", question: "Which feature distinguishes mammals?", options: ["Lay eggs", "Have scales", "Produce milk", "Cold-blooded"], correctIndex: 2, explanation: "Mammals produce milk." },
      { type: "question", question: "A frog belongs to which group?", options: ["Reptile", "Amphibian", "Fish", "Bird"], correctIndex: 1, explanation: "Frogs are amphibians." },
      { type: "question", question: "Which kingdom has no true nucleus?", options: ["Plantae", "Prokaryotes", "Fungi", "Protoctista"], correctIndex: 1, explanation: "Prokaryotes (bacteria)." },
      { type: "activity_of_integration", title: "Classification key", scenario: "Five animals: cat, snake, tilapia, eagle, frog.", task: "Create a yes/no key to identify each.", hint: "Broad questions first.", answer: "Has feathers? Yes=Eagle. No. Has legs? No=Tilapia. Yes. Dry scaly skin? Yes=Snake. No. Moist skin near water? Yes=Frog. No=Cat." },
    ],
  },

  // ===== TOPIC 4: INSECTS =====
  {
    id: "s1-bio-insects",
    topicId: "bio-insects",
    subjectId: "biology",
    title: "Insects",
    order: 4,
    estimatedMinutes: 16,
    passingScore: 70,
    isActive: true,
    curriculum: S1("Term 3", "Diversity of Living Things", 4, "Insects",
      "The learner understands the characteristics of insects and their importance in ecosystems."),
    blocks: [
      { type: "competency", text: "The learner should understand the characteristics of insects and their economic importance." },
      { type: "outcome", text: "Describe the general characteristics of insects.", tag: "k" },
      { type: "outcome", text: "Identify the body parts of an insect.", tag: "k,u" },
      { type: "outcome", text: "Explain the beneficial and harmful effects of insects.", tag: "u,v/a" },
      { type: "context", heading: "Insects are everywhere", content: "Insects are the most numerous animals on Earth. In Uganda, insects like mosquitoes, bees, butterflies, and termites affect our daily lives. Some spread diseases like malaria. Others pollinate our crops. Understanding insects is essential for health and agriculture." },
      { type: "key_point", title: "Characteristics of insects", content: "Insects have: three body parts (head, thorax, abdomen), six legs (three pairs), one pair of antennae, and usually one or two pairs of wings. They are arthropods, meaning they have a hard exoskeleton and jointed legs." },
      { type: "worked_example", problem: "Is a spider an insect? Give two reasons.", steps: ["An insect has three body parts and six legs.", "A spider has two body parts (cephalothorax and abdomen) and eight legs.", "A spider has no antennae.", "Conclusion: A spider is NOT an insect. It is an arachnid."], answer: "No, a spider is not an insect", reasoning: "The number of legs and body parts is the key distinguishing feature. Six legs and three body parts = insect. Eight legs and two body parts = arachnid." },
      { type: "key_point", title: "Beneficial and harmful insects", content: "BENEFICIAL: bees (pollinate crops, make honey), butterflies (pollination), ladybirds (eat pests). HARMFUL: mosquitoes (spread malaria), tsetse fly (sleeping sickness), locusts (destroy crops), termites (damage buildings). Some are both: flies can pollinate but also spread disease." },
      { type: "exam_style", scenario: "UNEB tests knowledge of insect body structure and its relation to function.", question: "Describe the body of a grasshopper. State three ways insects are important to humans.", marks: 5 },
      { type: "marking_guide", totalMarks: 5, criteria: [
        { criterion: "Three body parts: head, thorax, abdomen", marks: 1, type: "method" },
        { criterion: "Six legs, two pairs of wings, antennae", marks: 1, type: "method" },
        { criterion: "Importance 1: pollination (bees, butterflies)", marks: 1, type: "accuracy" },
        { criterion: "Importance 2: honey production", marks: 1, type: "accuracy" },
        { criterion: "Importance 3: pest control or disease vector", marks: 1, type: "communication" },
      ] },
      { type: "question", question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], correctIndex: 1, explanation: "Insects have six legs (three pairs)." },
      { type: "question", question: "How many body parts does an insect have?", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "Head, thorax, abdomen." },
      { type: "question", question: "A spider is NOT an insect because it has?", options: ["Wings", "Eight legs and two body parts", "No eyes", "No legs"], correctIndex: 1, explanation: "Spiders have eight legs and two body parts. Insects have six legs and three body parts." },
      { type: "question", question: "Which insect spreads malaria?", options: ["Bee", "Mosquito", "Butterfly", "Ladybird"], correctIndex: 1, explanation: "Female Anopheles mosquitoes spread malaria." },
      { type: "question", question: "Bees are beneficial because they?", options: ["Spread disease", "Pollinate crops and produce honey", "Destroy buildings", "Eat crops"], correctIndex: 1, explanation: "Bees pollinate flowers (essential for fruit) and produce honey." },
      { type: "activity_of_integration", title: "Malaria prevention", scenario: "Malaria is one of the biggest health challenges in Uganda. The Anopheles mosquito spreads it.", task: "Using your knowledge of insects, suggest three ways to reduce malaria in your community.", hint: "Think about the mosquito life cycle and habits.", answer: "1. Drain stagnant water where mosquitoes breed. 2. Use insecticide-treated mosquito nets at night. 3. Wear long sleeves in the evening when mosquitoes are active. 4. Use mosquito repellent. 5. Spray indoor walls with insecticide. Understanding the insect biology (breeds in water, bites at night) directly informs prevention strategies." },
    ],
  },

  // ===== TOPIC 5: FLOWERING PLANTS =====
  {
    id: "s1-bio-flowering-plants",
    topicId: "bio-flowering-plants",
    subjectId: "biology",
    title: "Flowering plants",
    order: 5,
    estimatedMinutes: 16,
    passingScore: 70,
    isActive: true,
    curriculum: S1("Term 3", "Diversity of Living Things", 5, "Flowering Plants",
      "The learner understands the structure and function of flowering plants."),
    blocks: [
      { type: "competency", text: "The learner should understand the external structure of flowering plants and the functions of each part." },
      { type: "outcome", text: "Identify the parts of a flowering plant.", tag: "k" },
      { type: "outcome", text: "State the functions of roots, stems, and leaves.", tag: "u" },
      { type: "outcome", text: "Identify the parts of a flower.", tag: "k,u" },
      { type: "context", heading: "Plants sustain life", content: "Plants produce the oxygen we breathe and the food we eat. In Uganda, crops like maize, beans, bananas, and coffee are flowering plants. Understanding their structure helps us grow more food and protect our environment." },
      { type: "key_point", title: "The main parts of a plant", content: "ROOTS: anchor the plant, absorb water and minerals. STEM: supports the plant, transports water up and food down. LEAVES: site of photosynthesis (making food) and transpiration (water loss). FLOWERS: reproductive organs. FRUIT: contains and protects seeds." },
      { type: "worked_example", problem: "Describe how water moves from the soil to the leaves of a plant.", steps: ["Root hairs absorb water from the soil by osmosis.", "Water moves up through the xylem vessels in the stem.", "Transpiration (water evaporating from leaves) pulls more water up.", "Water reaches the leaf cells where it is used for photosynthesis."], answer: "Roots absorb water, xylem transports it up, transpiration pulls it to leaves", reasoning: "This is like a straw. Evaporation at the top (transpiration) creates a pull that draws water up from the roots through the xylem tubes. The cohesion of water molecules keeps the column intact." },
      { type: "key_point", title: "Parts of a flower", content: "SEPAL: protects the flower bud. PETAL: attracts insects with colour and scent. STAMEN (male): made of anther (produces pollen) and filament. CARPEL/PISTIL (female): made of stigma (catches pollen), style, and ovary (contains eggs)." },
      { type: "question", question: "Which part of the plant absorbs water from the soil?", options: ["Leaves", "Stem", "Roots", "Flowers"], correctIndex: 2, explanation: "Roots (especially root hairs) absorb water and minerals." },
      { type: "question", question: "Where does photosynthesis mainly occur?", options: ["Roots", "Stem", "Leaves", "Flowers"], correctIndex: 2, explanation: "Leaves contain chlorophyll and are the main site of photosynthesis." },
      { type: "question", question: "Which part of the flower produces pollen?", options: ["Stigma", "Anther", "Petal", "Sepal"], correctIndex: 1, explanation: "The anther produces pollen grains (male sex cells)." },
      { type: "question", question: "The function of petals is to?", options: ["Absorb water", "Attract pollinators", "Produce seeds", "Support the plant"], correctIndex: 1, explanation: "Petals are colourful and scented to attract insects and birds for pollination." },
      { type: "activity_of_integration", title: "Why leaves are important", scenario: "A farmer removes too many leaves from his tomato plants hoping the fruits will grow bigger.", task: "Explain why removing leaves could actually harm the plant and reduce the harvest.", hint: "What do leaves do for the plant?", answer: "Leaves make food through photosynthesis. Removing them reduces the plant's ability to produce glucose, which the fruits need to grow. Fewer leaves means less food, smaller fruits, and a weaker plant. The farmer should keep healthy leaves on the plant. This shows how understanding plant biology directly affects farming practice." },
    ],
  },
];
